### ISSUE TITLE
Failed to build fsds_ros2_bridge: fatal error: yaml-cpp/yaml.h no such file or directory

### ISSUE THREAD

**Issue by FreddyTF** [FS-Driverless/Formula-Student-Driverless-Simulator#305]
trying to build the fsds_ros2_bridge with colcon build on ubuntu 20.04, ros galactic

here i am getting the following error message:

Starting >>> fs_msgs 
Finished <<< fs_msgs [0.54s]                     
Starting >>> fsds_ros2_bridge
--- stderr: fsds_ros2_bridge                             
In file included from /home/nodriver/Formula-Student-Driverless-Simulator/ros2/src/fsds_ros2_bridge/src/airsim_ros_wrapper.cpp:1:
/home/nodriver/Formula-Student-Driverless-Simulator/ros2/src/fsds_ros2_bridge/include/airsim_ros_wrapper.h:15:10: fatal error: yaml-cpp/yaml.h: No such file or directory
   15 | #include "yaml-cpp/yaml.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/airsim_ros.dir/build.make:63: CMakeFiles/airsim_ros.dir/src/airsim_ros_wrapper.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:200: CMakeFiles/airsim_ros.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< fsds_ros2_bridge [0.51s, exited with code 2]

Summary: 1 package finished [1.31s]
  1 package failed: fsds_ros2_bridge
  1 package had stderr output: fsds_ros2_bridge

**Comment by FreddyTF** [comment]
https://stackoverflow.com/questions/23656282/fatal-error-yaml-cpp-yaml-h-no-such-file-or-directory

solved
